# This workflow will check flake style
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs Deploy

on:
  push:
  #    branches: [ main, 'doc/*', 'dev/*' ]
  release:
    types: [ published ]

jobs:
  contents:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      matrix:
        python-version: [ 3.8 ]

    services:
      plantuml:
        image: plantuml/plantuml-server:jetty-v1.2023.6
        ports:
          - 18080:8080

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: ${{ github.event_name == 'push' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make wget curl cloc graphviz pandoc
          dot -V
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-doc.txt
      - name: Prepare dataset
        uses: nick-fields/retry@v2
        if: ${{ github.event_name == 'push' }}
        env:
          CI: 'true'
          HF_NARUGO_USERNAME: ${{ secrets.HF_NARUGO_USERNAME }}
          HF_NARUGO_PASSWORD: ${{ secrets.HF_NARUGO_PASSWORD }}
        with:
          shell: bash
          timeout_minutes: 20
          max_attempts: 5
          retry_on: any
          command: |
            make dataset
      - name: Generate the contents
        if: ${{ github.event_name == 'push' }}
        env:
          ENV_PROD: 'true'
          PLANTUML_HOST: http://localhost:18080
        run: |
          plantumlcli -c
          make docs
      - name: Change Commit
        if: ${{ github.event_name == 'push' }}
        id: commit
        run: |
          git config user.name 'narugo1992'
          git config user.email 'narugo@126.com'
          git add -A
          git diff-index --quiet HEAD || git commit -a -m "dev(narugo): auto sync $(date -R)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  doc:
    runs-on: ubuntu-latest
    needs:
      - contents
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        python-version: [ 3.8 ]

    services:
      plantuml:
        image: plantuml/plantuml-server:jetty-v1.2023.6
        ports:
          - 18080:8080

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make wget curl cloc graphviz pandoc
          dot -V
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-doc.txt
      - name: Prepare dataset
        uses: nick-fields/retry@v2
        env:
          CI: 'true'
          HF_NARUGO_USERNAME: ${{ secrets.HF_NARUGO_USERNAME }}
          HF_NARUGO_PASSWORD: ${{ secrets.HF_NARUGO_PASSWORD }}
        with:
          shell: bash
          timeout_minutes: 20
          max_attempts: 5
          retry_on: any
          command: |
            make dataset
      - name: Sync from ref
        if: ${{ github.event_name == 'push' }}
        run: |
          git pull
      - name: Generate
        env:
          ENV_PROD: 'true'
          PLANTUML_HOST: http://localhost:18080
        run: |
          git fetch --all --tags
          git branch -av
          git remote -v
          git tag
          plantumlcli -c
          make pdocs
          mv ./docs/build/html ./public
      - name: Deploy to Github Page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CONFIG_NAME: narugo1992
          GIT_CONFIG_EMAIL: narugo@126.com
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
